<a href="https://colab.research.google.com/github/AkshaySingh2005/numpy_basics./blob/main/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

*  Handling multi-dimensional arrays and matrices.
*  Performing mathematical operations on these arrays efficiently.











In [1]:
import numpy as np

In [23]:
print('1D Array')
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.size)
print(a.shape)
print(a.dtype)

#---------------------------

print('2D Array')
b = np.array([["a","b","c"],["d","e","f"]])
print(b)
print(type(b))
print(b.size)
print(b.shape)
print(b.dtype)

#---------------------------

print('3D Array')
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)
print(type(c))
print(c.size)
print(c.shape)
print(c.dtype)

1D Array
[1 2 3 4]
<class 'numpy.ndarray'>
4
(4,)
int64
2D Array
[['a' 'b' 'c']
 ['d' 'e' 'f']]
<class 'numpy.ndarray'>
6
(2, 3)
<U1
3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
<class 'numpy.ndarray'>
15
(1, 3, 5)
int64


In [32]:
print(b.transpose())
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])
print(a1+b1)
print(a1 * b1)


[['a' 'd']
 ['b' 'e']
 ['c' 'f']]
[5 7 9]
[ 4 10 18]


In [27]:
#random data -->default is float
print(np.empty((4,4),dtype=int))
print(np.zeros((3,5)))
print(np.ones((3,5),dtype=str))

[[   826752679            0 489626271861 433791696995]
 [498216206368 468151435365 476741369968 416611827826]
 [450971566194 519691042924 502511173664 416611827822]
 [416611827830 463856468073 420906795105 433791697004]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


In [44]:
print(np.arange(1,20))
print(np.arange(2,20,2))
ar = np.array([1,2,3,4])
print(ar.reshape(2,2))
print(ar.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14 16 18]
[[1 2]
 [3 4]]
[1 2 3 4]


In [53]:
arn = np.arange(1, 51).reshape(10, 5)
print(arn)

print(np.sum(arn, axis=0)) # Column-wise sum (vertical)
print(np.sum(arn, axis=1)) # Row-wise sum (horizontal)
print(np.mean(arn))
print(np.median(arn))
print(np.std(arn))
print(np.var(arn))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[235 245 255 265 275]
[ 15  40  65  90 115 140 165 190 215 240]
25.5
25.5
14.430869689661812
208.25


In [70]:
print(np.random.randint(1,10))
print(np.random.randint(1, 10, size=(5, 5)))
print(np.random.randn(5, 5))


7
[[7 4 1 4 4]
 [5 2 5 7 3]
 [7 3 1 9 5]
 [9 1 6 8 1]
 [9 6 9 3 9]]
[[ 0.40371709  0.66118027 -0.51884817 -0.32825954  1.48777824]
 [-0.75694489  1.36527994 -1.42795659 -1.35794299 -1.04889475]
 [ 0.312984    1.40671355 -0.68332963 -0.43121711 -0.32172413]
 [-0.25400767  1.31290678 -0.62922522  0.07556871 -0.09465429]
 [ 1.75571434  0.20812547  1.50241611  0.22602914  2.91208663]]
